# Generated by Django 4.0.4 on 2022-04-21 11:19

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(validators=[todo.models.validate_date]),
        ),
    ]
