# Generated by Django 4.0.2 on 2022-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_resetpasswordcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="week_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
