# Generated by Django 3.2 on 2022-05-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_task_week_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="overdue",
        ),
    ]
